=== sriram005/WAD-JAVA-LAB-EXERCISES/XML/store/store.dtd
<!ELEMENT store (shop+)>
<!ELEMENT shop (Shop_name,Shop_location,Total_items,Home_delivery,Total_revenue)>
<!ELEMENT Shop_name (#PCDATA)>
<!ELEMENT Shop_location (#PCDATA)>
<!ELEMENT Total_items (#PCDATA)>
<!ELEMENT Home_delivery (#PCDATA)>
<!ELEMENT Total_revenue (#PCDATA)>

=== sriram005/WAD-JAVA-LAB-EXERCISES/XML/store/retail-store.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE store SYSTEM "store.dtd">
<store>
    <shop>
        <Shop_name>ABC Store</Shop_name>
        <Shop_location>Chennai</Shop_location>
        <Total_items>500</Total_items>
        <Home_delivery>Yes</Home_delivery>
        <Total_revenue>50000</Total_revenue>
    </shop>
    <shop>
        <Shop_name>DEF Store</Shop_name>
        <Shop_location>Coimbatore</Shop_location>
        <Total_items>750</Total_items>
        <Home_delivery>No</Home_delivery>
        <Total_revenue>100000</Total_revenue>
    </shop>
</store>
